# Generated by Django 4.2.1 on 2023-06-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Pakaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakaian', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Alamat', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(null=True)),
                ('Jenis_Pakaian_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pelanggan.jenis_pakaian')),
            ],
        ),
    ]
